### ISSUE TITLE
Add escape sequences to code [\n]

### ISSUE THREAD

**Issue by deavmi** [deavmi/BoaGen#14]
Add the newline escape sequence `\n` to the code, as this will help with the `echo` command and as well as using this for making the script append text on a newline. Rather than using several blank printouts.

**e.g.**
````bash
echo ""
echo "Hello World"
echo ""
````

As compared to:

**e.g**

````bash
echo "\nHello World\n"
````

**Comment by Walkman100** [comment]
Can i do this?

**Comment by deavmi** [comment]
Imma' do it. As part of my learning of bash. But thanks anyway

**Comment by deavmi** [comment]
Done
